### ISSUE TITLE
Add support for Neovim

### ISSUE THREAD

**Issue by Limero** [praiskup/vim-ale-rpm#1]
On Arch Linux, installing the `vim-ale` package will make it work right away with both Vim and Neovim. I noticed after installing your package from COPR that it only works with Vim. It seems that on Arch, Neovim and Vim share a directory for plugins, but they are separate on Fedora.

As an example, installing `fzf` on Fedora will install the plugin to these directories:

```
/usr/share/nvim/site/plugin/fzf.vim
/usr/share/vim/vimfiles/plugin/fzf.vim
```

But on Arch Linux only:

```
/usr/share/vim/vimfiles/plugin/fzf.vim
```

It would be great if this package copied its files to both directories and worked right away with Neovim as well :smile:

**Comment by praiskup** [comment]
Thank you for the feedback!

I guess it is not only about `ale.vim`, but I'd have to copy every single file into two separate directories?

Tried just the ale.vim, and it wrote:

```
Error detected while processing /usr/share/nvim/runtime/plugin/ale.vim:
line  289:
E117: Unknown function: ale#events#Init
Press ENTER or type command to continue
```

But copying everyting twice is quite ugly, whould we wrap nvim related tree into
a separate sub-package?

Perhaps we could in parallel request vim/nvim in Fedora to share the plugin
directories?

Otherwise, I'm afraid I won't have enough time soon for working on this.  Help
with patch would be welcome!

**Comment by Limero** [comment]
I guess every single file would have to be copied. I looked at some of the other packaged vim-plugins for Fedora and they seem to only copy the files for Vim, so they wouldn't work either.

Arch Linux makes their Neovim package load the regular Vim plugins, and if I add the same to my config on Fedora, your package works great. https://github.com/archlinux/svntogit-community/blob/packages/neovim/trunk/PKGBUILD#L51

If the Fedora maintainers for Neovim would be interested in adding regular Vim plugin loading like Arch Linux, that would probably be the best solution. I agree doubling all files in the package is ugly.

**Comment by Limero** [comment]
I have opened a bug for the Fedora package of Neovim here https://bugzilla.redhat.com/show_bug.cgi?id=1909495

**Comment by praiskup** [comment]
Would it be acceptable to have a separate sub-package, like neovim-ale?

**Comment by Limero** [comment]
I just tried the separate package and that works well. Thank you!

**Comment by Limero** [comment]
Neovim on Fedora now loads regular vim-plugins just like on Arch, so by installing the regular `vim-ale` package it works on both vim and neovim. Installing the `vim-ale` package will install regular vim as a dependency, so keeping it as two separate packages might still be a good idea, or making vim an optional dependency instead.

Or would something like this work?
```
Requires: (vim or neovim)
```

**Comment by praiskup** [comment]
> Or would something like this work?

I guess yes.  Should we have a conditional for older and newer Fedora versions?
